//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public int UserID { get; set; }
        public string TargetType { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Review Review { get; set; }
        public virtual User User { get; set; }
    }
}
